# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [2]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [3]:
# Create a 1-dimensional NumPy array using np.array()
a1 = np.array([1,2,3])

# Create a 2-dimensional NumPy array using np.array()
a2 = np.array([[1,2,3],
                [4,5,6]])

# Create a 3-dimensional Numpy array using np.array()
a3 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
a1.ndim,a2.ndim,a3.ndim

(1, 2, 3)

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [8]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
print(a1.ndim)
print(type(a1))
print(a1.dtype)
a1.size


1
<class 'numpy.ndarray'>
int64


3

In [9]:
# Attributes of 2-dimensional array
print(a2.ndim)
print(type(a2))
print(a2.dtype)
a2.size



2
<class 'numpy.ndarray'>
int64


6

In [10]:
# Attributes of 3-dimensional array
# Attributes of 2-dimensional array
print(a3.ndim)
print(type(a3))
print(a3.dtype)
a3.size


3
<class 'numpy.ndarray'>
int64


9

In [12]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
df = pd.DataFrame(a2)
df


0  1  2
0  1  2  3
1  4  5  6

In [14]:
# Create an array of shape (10, 2) with only ones
ones = np.ones((10,2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [16]:
# Create an array of shape (7, 2, 3) of only zeros
zeros = np.zeros((7,2,3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [18]:
# Create an array within a range of 0 and 100 with step 3
array_range = np.arange(0,100,3)
array_range

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [21]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
array_random = np.random.randint(0,10,size=(7,2))
array_random

array([[6, 8],
       [4, 1],
       [9, 6],
       [8, 6],
       [1, 6],
       [1, 7],
       [8, 0]])

In [28]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
array_random_0_1 = np.random.random(size=(3,5))
array_random_0_1

array([[0.87642473, 0.12300573, 0.84064032, 0.86839111, 0.84620746],
       [0.1612481 , 0.52710755, 0.88917199, 0.77770779, 0.30090441],
       [0.33515615, 0.62493722, 0.47501969, 0.73265976, 0.60229019]])

In [31]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
random_array_4 = np.random.randint(10,size=(4,6))
random_array_4

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [35]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
random_array = np.random.randint(10,size=(3,7))
np.unique(random_array)
# Find the unique numbers in the array you just created


array([0, 1, 2, 4, 6, 7, 8, 9])

In [39]:
# Find the 0'th index of the latest array you created
random_array[0][0]
random_array

array([[0, 7, 2, 2, 0, 4, 9],
       [6, 9, 8, 6, 8, 7, 1],
       [0, 6, 6, 7, 4, 2, 7]])

In [38]:
# Get the first 2 rows of latest array you created
random_array[:2]

array([[0, 7, 2, 2, 0, 4, 9],
       [6, 9, 8, 6, 8, 7, 1]])

In [40]:
# Get the first 2 values of the first 2 rows of the latest array
random_array[:2,:2]

array([[0, 7],
       [6, 9]])

In [43]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
number_random_1 = np.random.randint(0,10,size=(3,5))
number_random_2 = np.random.randint(0,10,size=(3,5))
number_random_1

array([[5, 3, 9, 6, 8],
       [6, 0, 0, 8, 8],
       [3, 8, 2, 6, 5]])

In [44]:
number_random_2

array([[7, 8, 4, 0, 2],
       [9, 7, 5, 7, 8],
       [3, 0, 0, 9, 3]])

In [45]:
# Add the two arrays together
number_random_1 + number_random_2

array([[12, 11, 13,  6, 10],
       [15,  7,  5, 15, 16],
       [ 6,  8,  2, 15,  8]])

In [46]:
# Create another array of ones of shape (5, 3)
number_random_3 = np.random.randint(0,10,size=(5,3))
number_random_3

array([[6, 1, 2],
       [0, 4, 0],
       [7, 0, 0],
       [1, 1, 5],
       [6, 4, 0]])

In [48]:
# Try add the array of ones and the other most recent array together
number_random_3.T + number_random_2

array([[13,  8, 11,  1,  8],
       [10, 11,  5,  8, 12],
       [ 5,  0,  0, 14,  3]])

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?
Matrix chuyen vi transope

In [52]:
# Create another array of ones of shape (3, 5)
number_random_4 = np.random.randint(10,size=(3,5))

In [54]:
# Subtract the new array of ones from the other most recent array
number_random_4 - number_random_1

array([[-5, -1, -8, -2,  1],
       [-1,  6,  3, -2, -1],
       [-3, -3,  5, -2, -2]])

In [55]:
# Multiply the ones array with the latest array
number_random_1 * number_random_2

array([[35, 24, 36,  0, 16],
       [54,  0,  0, 56, 64],
       [ 9,  0,  0, 54, 15]])

In [56]:
# Take the latest array to the power of 2 using '**'
number_random_4 ** 2

array([[ 0,  4,  1, 16, 81],
       [25, 36,  9, 36, 49],
       [ 0, 25, 49, 16,  9]])

In [60]:
number_random_4

array([[0, 2, 1, 4, 9],
       [5, 6, 3, 6, 7],
       [0, 5, 7, 4, 3]])

In [58]:
# Do the same thing with np.square()
np.square(number_random_4)

array([[ 0,  4,  1, 16, 81],
       [25, 36,  9, 36, 49],
       [ 0, 25, 49, 16,  9]])

In [61]:
# Find the mean of the latest array using np.mean()
np.mean(number_random_4)

4.133333333333334

In [62]:
# Find the maximum of the latest array using np.max()
np.max(number_random_4)

9

In [63]:
# Find the minimum of the latest array using np.min()
np.min(number_random_4)

0

In [64]:
# Find the standard deviation of the latest array
np.std(number_random_4)

2.578543947441829

In [65]:
# Find the variance of the latest array
np.var(number_random_4)

6.648888888888888

In [67]:
# Reshape the latest array to (3, 5, 1)
number_random_4.reshape(3,5,1).shape

(3, 5, 1)

In [68]:
# Transpose the latest array
number_random_4.T

array([[0, 5, 0],
       [2, 6, 5],
       [1, 3, 7],
       [4, 6, 4],
       [9, 7, 3]])

What does the transpose do?

Swich row to -> colum

In [72]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
np.random.seed(2)
int_rand_1 = np.random.randint(0,10,size=(3,3))
int_rand_1

array([[8, 8, 6],
       [2, 8, 7],
       [2, 1, 5]])

In [74]:
# Perform a dot product on the two newest arrays you created
np.random.seed(3)
int_rand_2 = np.random.randint(0,10,size=(3,2))
np.dot(int_rand_1,int_rand_2)

array([[136, 136],
       [ 96,  82],
       [ 59,  26]])

In [76]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
rd1 = np.random.randint(0,10,size=(4,3))
rd2 = np.random.randint(0,10,size=(4,3))
np.dot(rd1,rd2.T)

array([[57, 55,  9, 53],
       [61, 63, 10, 58],
       [58, 98, 13, 65],
       [61, 73, 11, 59]])

In [36]:
# Perform a dot product on the two newest arrays you created
np.dot(rd1,rd2.T)

It doesn't work. How would you fix it?

dot two matrix make r1 cl_1 * r2 cl2 ( r2 = col_1)

In [77]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
np.dot(rd1,rd2.T)

array([[57, 55,  9, 53],
       [61, 63, 10, 58],
       [58, 98, 13, 65],
       [61, 73, 11, 59]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [83]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
r_d_1 = np.random.randint(0,10,size=(3,4))
r_d_2 = np.random.randint(0,10,size=(3,4))

In [79]:
# Compare the two arrays with '>'
r_d_1 > r_d_2 

array([[ True, False, False, False],
       [False, False, False,  True],
       [ True, False,  True, False]])

What happens when you compare the arrays with `>`?

In [80]:
# Compare the two arrays with '>='
r_d_1 >= r_d_2 

array([[ True, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True, False]])

In [84]:
# Find which elements of the first array are greater than 7
r_d_1[r_d_1 > 7]

array([8, 8, 9, 8])

In [85]:
# Which parts of each array are equal? (try using '==')
r_d_1 == r_d_2

array([[False, False, False, False],
       [False,  True, False, False],
       [False, False, False, False]])

In [86]:
# Sort one of the arrays you just created in ascending order

np.sort([23,2,25])

array([ 2, 23, 25])

In [88]:
# Sort the indexes of one of the arrays you just created
np.argsort(r_d_2)

array([[1, 2, 0, 3],
       [1, 3, 0, 2],
       [2, 1, 3, 0]])

In [89]:
# Find the index with the maximum value in one of the arrays you've created
np.argmin(r_d_2)

1

In [90]:
# Find the index with the minimum value in one of the arrays you've created
np.argmax(r_d_2)

6

In [91]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmin(r_d_2,axis=1)

array([1, 1, 2])

In [92]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(r_d_2,axis=0)

array([1, 0, 0, 1])

In [95]:
# Create an array of normally distributed random numbers
np.random.rand(3,1)

array([[0.151861  ],
       [0.10010434],
       [0.12929386]])

In [96]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1, 100, 10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.